Update .chezmoiignore Update dot_bash_aliases

diff --git a/dot_bash_aliases b/dot_bash_aliases
--- a/dot_bash_aliases
+++ b/dot_bash_aliases
@@ -1,2 +1,67 @@
+# builtin-colorize
+alias diff='diff --color=auto'
+alias grep='grep --color=auto'
+alias ls='ls -alhF --color=auto'
+alias ip='ip -color=auto'
+# builtin-utility
+## search
+alias 'ps?'='ps ax | grep '
+alias 'lsof?'='lsof -i -P | grep -i '
+## cd
+alias ..='cd ..'
+alias ...='cd ../..'
+alias ....='cd ../../..'
+alias .....='cd ../../../..'
+## git
+alias g='git'
+alias ga='git add'
+alias gd='git diff'
+alias gs='git status'
+alias gp='git push'
+alias gb='git branch'
+alias gst='git status'
+alias gco='git checkout'
+alias gf='git fetch'
+alias gc='git commit'
+alias cdg='cd $(git rev-parse --show-toplevel)'  # cd to .git
+## safety
+alias cp='cp -i'
+alias mv='mv -i'
+alias rm='rm -i'
+
+# docker
+alias dcu='docker-compose up -d'
+alias dcd='docker-compose down'
+alias dcr='docker-compose restart'
+alias dp='docker ps'
+alias dx='docker exec -it'
+alias dr='docker run -it --rm=true'
+# chezmoi ("dotfile")
 alias dotfile='chezmoi'
 alias dotfile-cd='pushd $(chezmoi source-path) > /dev/null 2>&1 || exit'
+
+#######################################
+# chaet
+# Arguments:
+#   command you want to cheat
+# Returns:
+#   0 is ok, non-zero on error.
+#######################################
+cheat () {
+  curl cheat.sh/"$1"
+}
+
+#######################################
+# switch file to back/front
+# Arguments:
+#   $1: back or front
+#   $2: file path
+# Returns:
+#   0 is ok, non-zero on error.
+#######################################
+switch () {
+  if [ $# != 2 ]; then echo "switch: argument error." >&2; return 1; fi
+  if [ $1 = "back" ]; then mv -i $2{,.bak};
+  elif [ $1 = "front" ]; then mv -i $2{.bak,};
+  else echo "switch: argument parse error $1." >&2 ; fi
+}
