Update dot_bash_aliases

diff --git a/dot_bash_aliases b/dot_bash_aliases
--- a/dot_bash_aliases
+++ b/dot_bash_aliases
@@ -84,8 +84,8 @@ if [ "$(command -v peco)" ]; then
   ### singleline search
   ### https://kohkimakimoto.hatenablog.com/entry/2014/06/28/163412
   _peco_snippets() {
-    if [ ! -e ~/.snippets ]; then
-        echo "~/.snippets is not found." >&2
+    if [ ! -e $HOME/.snippets ]; then
+        echo "$HOME/.snippets is not found." >&2
         return 1
     fi
     local line
