Update private_dot_local/bin/my_own/executable_daemon Add private_dot_local/state/my_own/log/empty_dot_gitkeep Add test.log

diff --git a/private_dot_local/bin/my_own/executable_daemon b/private_dot_local/bin/my_own/executable_daemon
--- a/private_dot_local/bin/my_own/executable_daemon
+++ b/private_dot_local/bin/my_own/executable_daemon
@@ -1,20 +1,27 @@
 #!/usr/bin/env bash
 #
-# bash wrapper.
-# * always eo pipefail (error, pipe fail)
-# * debug shell loading (see _debug)
-# * log loading (see _log)
-# e.g. MY_OWN__DEBUG=1 bash_wrapper echo hello
-
-[ "$#" -lt 1 ] && exit 1;
-
-set -eo pipefail
+# daemon wrapper.
+# stdin disabled (for githubactions. (related to tty?))
+#
+# Arguments:
+#   stdout path
+#   stderr path
+#   command
 
 . _log
 
-if [ "$(command -v $1)" ]; then
-  _command=$1
-  shift
-  eval ". _debug; $_command" "$@"
-  unset _command
+[ "$#" -lt 3 ] && exit 1;
+_stdout=$1
+shift
+_stderr=$1
+shift
+
+logger_note "daemon starting... $*"
+nohup /bin/bash -c "$*" 1> $_stdout 2> $_stderr - /dev/null &
+if [ $? = 0 ]; then
+  logger_success "daemon started."
+else
+  logger_error "daemon failed."
+  wait
+  exit 2
 fi
