Update .chezmoiignore Update dot_bashrc.tmpl Update dot_profile.tmpl Add private_dot_local/bin/my_own/executable_dotenv_export Update private_dot_local/bin/my_own/executable_proxy_switch

diff --git a/private_dot_local/bin/my_own/executable_proxy_switch b/private_dot_local/bin/my_own/executable_proxy_switch
--- a/private_dot_local/bin/my_own/executable_proxy_switch
+++ b/private_dot_local/bin/my_own/executable_proxy_switch
@@ -6,24 +6,18 @@
 # tool specific:
 #   npm : global
 
-. $HOME/.local/bin/my_own/_log
-. $HOME/.local/bin/my_own/_gather_facts
+. ${MY_OWN_BIN_PATH}/_log
+. ${MY_OWN_BIN_PATH}/_gather_facts
 
-# proxy scheme and authority
-# https://www.rfc-editor.org/rfc/rfc3986#section-3
-HTTP_SCHEME_AUTHORITY="http://proxy:8080"
-HTTPS_SCHEME_AUTHORITY="https://proxy:8080"
-FTP_SCHEME_AUTHORITY="ftp://proxy:21"
-NO_PROXY_HOST="127.0.0.1,localhost,${HOSTNAME}"
 # edit flag
 EDIT_ETC_ENVIRONMENT=""
 EDIT_SHELLRC=""
 EDIT_NPM=""
 
-SHELLRC=$HOME/.bashrc
-BACKUP_DIR="${XDG_STATE_HOME:-$HOME/.local/state}/my_own/proxy/backup"
+readonly SHELLRC=$HOME/.bashrc
+readonly BACKUP_DIR="${MY_OWN_STATE_PATH}/proxy/backup"
 
-INSERT_LABEL="# This section was generated by $HOME/.local/bin/my_own/proxy_switch"
+readonly INSERT_LABEL="# This section was generated by $MY_OWN_BIN_PATH/proxy_switch"
 
 
 cancel() {
@@ -43,14 +37,24 @@ elif [ $1 != "on" ] && [ $1 != "off" ]; then
   exit 2
 else
   log_note "backup dir: $BACKUP_DIR"
-  log_note "edit valus:$(cat <<EOF
+  if [ $1 = "on" ]; then
+    if [ -e "${MY_OWN_SHARE_PATH}/secret/proxy.orig" ]; then 
+      log_note "edit proxy:"
+      "${MY_OWN_SHARE_PATH}/secret/proxy.orig"
+    else
+      log_error "proxy_switch: proxy.orig not found."
+      exit 1
+    fi
+  else
+    log_note "edit proxy:$(cat <<EOF
 
-http_proxy $HTTP_SCHEME_AUTHORITY
-https_proxy $HTTPS_SCHEME_AUTHORITY
-ftp_proxy $FTP_SCHEME_AUTHORITY
-no_proxy $NO_PROXY_HOST
+http_proxy (off)
+https_proxy (off)
+ftp_proxy (off)
+no_proxy (off)
 EOF
-  )"
+    )"
+  fi
   # select files you want to edit
   read -n1 -p "edit /etc/environment? (y/N): " yn; case "$yn" in [yY]*) EDIT_ETC_ENVIRONMENT="true"; echo "," ;; *) echo ", skip";; esac
   read -n1 -p "edit $SHELLRC? (y/N): " yn; case "$yn" in [yY]*) EDIT_SHELLRC="true"; echo "," ;; *) echo ", skip";; esac
@@ -58,11 +62,15 @@ EOF
 
   read -n1 -p "$(log_warning "ok? (y/N): ")" yn; case "$yn" in [yY]*) echo "";; *) exit 1;; esac
 
+  if [ $1 = "on" ] && [ ! -e "${MY_OWN_SHARE_PATH}/secret/proxy.orig" ]; then 
+    log_error "proxy_switch: proxy.orig not found."
+    exit 1
+  fi
+
   ## backup and delete previous values
   if [ -e "/etc/environment" ] && [ -n "$EDIT_ETC_ENVIRONMENT" ] ; then
     log_note "clear proxy ➔ /etc/environment"
     eval "$(get_escalation_method)" sed -i.bak \
-      -e "/proxy_switch/Id" \
       -e "/http_proxy/Id" -e "/HTTP_PROXY/Id" \
       -e "/https_proxy/Id" -e "/HTTPS_PROXY/Id" \
       -e "/ftp_proxy/Id" -e "/FTP_PROXY/Id" \
@@ -71,45 +79,16 @@ EOF
     eval "$(get_escalation_method)" mv /etc/environment.bak $BACKUP_DIR
     if [ $1 = "on" ]; then
       log_warning "set proxy ➔ /etc/environment"
-      eval "$(get_escalation_method)" tee -a /etc/environment <<EOF
-$INSERT_LABEL \
-
-http_proxy=$HTTP_SCHEME_AUTHORITY
-HTTP_PROXY=$HTTP_SCHEME_AUTHORITY
-https_proxy=$HTTPS_SCHEME_AUTHORITY
-HTTPS_PROXY=$HTTPS_SCHEME_AUTHORITY
-ftp_proxy=$FTP_SCHEME_AUTHORITY
-FTP_PROXY=$FTP_SCHEME_AUTHORITY
-no_proxy=$NO_PROXY_HOST
-NO_PROXY=$NO_PROXY_HOST
-EOF
-    fi
+      "${MY_OWN_SHARE_PATH}/secret/proxy.orig"  | eval "$(get_escalation_method)" tee -a /etc/environment
+     fi
   fi
 
   if [ -e "$SHELLRC" ] && [ -n "$EDIT_SHELLRC" ] ; then
     log_note "clear proxy ➔ $SHELLRC"
-    sed -i.bak \
-      -e "/proxy_switch/Id" \
-      -e "/http_proxy/Id" -e "/HTTP_PROXY/Id" \
-      -e "/https_proxy/Id" -e "/HTTPS_PROXY/Id" \
-      -e "/ftp_proxy/Id" -e "/FTP_PROXY/Id" \
-      -e "/no_proxy/Id" -e "/NO_PROXY/Id" \
-       $SHELLRC
-    mv $SHELLRC.bak $BACKUP_DIR
+    [ -L ${MY_OWN_SHARE_PATH}/secret/proxy ] && [ -e ${MY_OWN_SHARE_PATH}/secret/proxy ] && unlink ${MY_OWN_SHARE_PATH}/secret/proxy
     if [ $1 = "on" ]; then
       log_warning "set proxy ➔ $SHELLRC"
-      tee -a $SHELLRC <<EOF
-$INSERT_LABEL \
-
-export http_proxy=$HTTP_SCHEME_AUTHORITY
-export HTTP_PROXY=$HTTP_SCHEME_AUTHORITY
-export https_proxy=$HTTPS_SCHEME_AUTHORITY
-export HTTPS_PROXY=$HTTPS_SCHEME_AUTHORITY
-export ftp_proxy=$FTP_SCHEME_AUTHORITY
-export FTP_PROXY=$FTP_SCHEME_AUTHORITY
-export no_proxy=$NO_PROXY_HOST
-export NO_PROXY=$NO_PROXY_HOST
-EOF
+      ln -s ${MY_OWN_SHARE_PATH}/secret/proxy.orig ${MY_OWN_SHARE_PATH}/secret/proxy
     fi
   fi
 
@@ -122,7 +101,8 @@ EOF
     npm -g config set registry "https://registry.npmjs.org/"
     if [ $1 = "on" ]; then
       log_warning "set proxy ➔ npm"
-      npm -g config set proxy "$HTTP_SCHEME_AUTHORITY"
+      eval "$(${MY_OWN_SHARE_PATH}/secret/proxy.orig)"
+      npm -g config set proxy "$http_proxy"
       npm -g config set registry "http://registry.npmjs.org/"
     fi
   fi
